// src/components/content/data.tsx
import React from 'react';

const data = [
  ['Boundary Polygons', 'polygons', '4.60 GB', '1.18 GB'],
  ['Cartographic Lines', 'lines', '752 MB', '614 MB'],
  ['Label Points', 'points', '19.9 MB', '11.8 MB'],
];

const sources = [
  [
    'Coastlines',
    'OSM',
    'https://osmdata.openstreetmap.de/data/land-polygons.html',
  ],
  ['Admin 0', 'UN GIS', 'https://data.humdata.org/dataset/united-nations-map'],
  ['Admin 1-4 Primary', 'OCHA', 'https://cod.unocha.org'],
  ['Admin 1-4 Secondary', 'GADM', 'https://gadm.org/data.html'],
];

export default () => (
  <>
    <h1 className="has-text-centered">Global Edge-Matched Admin Data</h1>
    <p>
      The Global Admin project is a data processing pipeline designed to take
      the best available administration boundary information from multiple
      sources (OCHA, government, OSM, GADM, etc), aggregating them into a single
      edge-matched dataset with a common schema using an automated methodology.
      The most detailed admin level available is used, ranging from 0-4
      depending on the source. This dataset uses ISO-3 codes as the primary unit
      of edge-matching, with{' '}
      <a href="https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv">
        249
      </a>{' '}
      currently used (not including disputed areas). Of these, 227 ISO-3 codes
      have subdivisions available: 114 sourced from OCHA, 106 from GADM, and 7
      from public government data repositories. All these sources are matched to
      an admin 0 dataset produced by the UN Geospatial Information Section, and
      coastlines produced by OpenStreetMap. Data can be downloaded from the
      following links (updated weekly), last updated Tuesday, 02 February, 2021:
    </p>
    <div className="table-container">
      <table className="table">
        <thead>
          <tr>
            <th>Layer (ADM 0-4)</th>
            <th>GeoPackage (GPKG)</th>
            <th>File Geodatabase (GDB)</th>
          </tr>
        </thead>
        <tbody>
          {data.map(([name, layer, size1, size2]) => (
            <tr key={layer}>
              <td>{name}</td>
              <td>
                <a
                  href={`https://data.fieldmaps.io/global-admin/wld_${layer}.gpkg.zip`}
                >
                  {`wld_${layer}.gpkg.zip (${size1})`}
                </a>
              </td>
              <td>
                <a
                  href={`https://data.fieldmaps.io/global-admin/wld_${layer}.gdb.zip`}
                >
                  {`wld_${layer}.gdb.zip (${size2})`}
                </a>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
    <h2 className="has-text-centered">Sources</h2>
    <p>
      The following links point to data catalogues used for this project, all
      data manually downloaded, and some transformations performed. These are
      some of the modifications performed on each source as a pre-processing
      step:
      <ul>
        <li>
          <b>OCHA</b>: Boundary modifications are mostly limited to areas
          involving disputed boundaries, such as both Sudan and South Sudan
          claiming the Abyei Administrative Region. In this case, the area is
          removed from both countries when performing edge-matching, and
          represented as a disputed area in the admin 0 layer. In rare cases,
          topology cleaning is also required. For attributes that have not been
          formatted to the ITOS geodatabase standard, as defined by documents on{' '}
          <a href="https://github.com/UGA-ITOSHumanitarianGIS/mapservicedoc">
            GitHub
          </a>
          , tables are manually changed to match this so they can be
          automatically read.
        </li>
        <li>
          <b>GADM</b>: Lakes and water bodies are classified as administrative
          regions with no names in this dataset, and are therefore removed
          before performing edge-matching.
        </li>
      </ul>
    </p>
    <div className="table-container">
      <table className="table">
        <thead>
          <tr>
            <th>Layer</th>
            <th>Source</th>
          </tr>
        </thead>
        <tbody>
          {sources.map(([layer, source, url]) => (
            <tr>
              <td>{layer}</td>
              <td>
                <a href={url}>{source}</a>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
    <h2 className="has-text-centered">Boundary Normalization</h2>
    <p>
      A common problem of merging spatial data from different sources is the
      existence of gaps and overlaps between sources. There are many ways to
      address this problem, with the approach taken here being to generate
      borderless digital boundary files for each input. In this context, a
      digital boundary file is one that does not follow shorelines and
      international boundaries, but rather stretches out with simplified edges,
      intended for users to clip with their own shorelines and international
      boundaries. For example, Statistics Canada uses a digital boundary file
      when creating census blocks, later clipped with lakes and shorelines to
      derive a layer suitable for reference maps.
    </p>
    <p className="has-text-centered">
      <a href="https://www150.statcan.gc.ca/n1/pub/92-195-x/2011001/other-autre/carto-eng/carto-eng.htm">
        <img
          src="/img/cbf-vs-dbf.png"
          alt="cartographic vs digital boundary file"
        />
      </a>
    </p>
    <h2 className="has-text-centered">Attribute Normalization</h2>
    <p>
      Just as with boundaries, merging attribute columns between sources with
      different schemas need to be conditioned so that columns align with each
      other. The following schema is used.
    </p>
    <h3 className="has-text-centered">Repeating in layer</h3>
    <p>
      The following columns repeat for each higher level in an admin layer. An
      admin 2 layer will include attributes for adm2, adm1, and adm0. Replace
      the "X" with the indicated level.
    </p>
    <div className="table-container">
      <table className="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>admX_id</td>
            <td>
              Automatically generated ID used for internal pipeline management.
            </td>
          </tr>
          <tr>
            <td>admX_ocha</td>
            <td>
              P-Code taken from OCHA sources. If not an OCHA source, a P-Code
              like ID is generated using the ISO-2 code.
            </td>
          </tr>
          <tr>
            <td>admX_name1</td>
            <td>
              Primary administrative region name. Uses the language defined by
              the "lang_name1" column.
            </td>
          </tr>
          <tr>
            <td>admX_name2</td>
            <td>
              Secondary administrative region name. Uses the language defined by
              the "lang_name2" column.
            </td>
          </tr>
          <tr>
            <td>admX_name3</td>
            <td>
              Tertiary administrative region name. Uses the language defined by
              the "lang_name3" column.
            </td>
          </tr>
          <tr>
            <td>admX_namea</td>
            <td>
              All other names listed for a region are combined together using
              the pipe ( | ) symbol.
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <h3 className="has-text-centered">Once per layer</h3>
    <p>
      These columns only appear a single time per layer, providing layer
      metadata.
    </p>
    <div className="table-container">
      <table className="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>lang_name1</td>
            <td>Primary language used for "admX_name1".</td>
          </tr>
          <tr>
            <td>lang_name2</td>
            <td>Secondary language used for "admX_name2".</td>
          </tr>
          <tr>
            <td>lang_name3</td>
            <td>Tertiary language used for "admX_name3".</td>
          </tr>
          <tr>
            <td>src_name</td>
            <td>One of: OCHA, GOVT, GADM.</td>
          </tr>
          <tr>
            <td>src_url</td>
            <td>Link where the original data source can be downloaded.</td>
          </tr>
          <tr>
            <td>src_date</td>
            <td>Date original dataset was produced.</td>
          </tr>
          <tr>
            <td>src_valid</td>
            <td>Last date original dataset was reviewed.</td>
          </tr>
          <tr>
            <td>adm_max</td>
            <td>
              Most detailed administrative level available for a particular
              ISO-3 region.
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <h3 className="has-text-centered">Only in admin 0</h3>
    <p>These columns only appear in the admin 0 layer.</p>
    <div className="table-container">
      <table className="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>adm0_fid</td>
            <td>
              Feature ID code used to differentiate states and self-governing
              territories sharing the same ISO-3 code.
            </td>
          </tr>
          <tr>
            <td>adm0_name</td>
            <td>
              Romanized name associated to the region defined by adm0_fid.
            </td>
          </tr>
          <tr>
            <td>adm0_label</td>
            <td>Map label to be used for a region defined by adm0_fid.</td>
          </tr>
          <tr>
            <td>adm0_cont</td>
            <td>Code of the continent a given ISO-3 belongs to.</td>
          </tr>
          <tr>
            <td>adm0_color</td>
            <td>
              When creating thematic maps, features sharing the same value for
              this column should be coloured together.
            </td>
          </tr>
          <tr>
            <td>adm0_stsc</td>
            <td>
              Indicates the sovereignty status code of the region given as an
              integer.
            </td>
          </tr>
          <tr>
            <td>adm0_stsn</td>
            <td>
              Indicates the sovereignty status of the region (State, Territory,
              Special Region, etc).
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </>
);

// src/routes/data.svelte
<svelte:head>
  <title>Data | Fieldmaps.io</title>
</svelte:head>

<div class="content">
  <h1 id="global-admin">Global Admin</h1>
  <p>
    The Fieldmaps Global Admin project is a data processing pipeline designed to
    take the &quot;best available&quot; administration boundary information from
    multiple sources and aggregate them into a single dataset. By normalizing
    inputs in this way, the intent is to ease the process for derivative
    products at the global level to be automatically generated. Data processing
    is done to create standardization for both spatial and tabular aspects of
    boundary data.
  </p>
  <h2 id="get-the-data">Get the Data</h2>
  <p>
    <img
      src="https://raw.githubusercontent.com/fieldmaps/global-admin/master/images/coverage.png"
      alt="dataset coverage" />
  </p>
  <p>
    At its current stage, this project is undergoing active development, with
    schemas and download links subject to change. Currently, data is available
    for over 100 countries originating from
    <a href="https://data.humdata.org/search?ext_cod=1">
      Humanitarian Data Exchange
    </a>
    , with remaining countries sourced from
    <a href="https://gadm.org/data.html">GADM</a>
    . A full breakdown of sources and metadata is available
    <a href="https://github.com/fieldmaps/global-admin/blob/master/data.csv">
      here
    </a>
    .
  </p>
  <ul>
    <li>
      Boundaries (most detailed level only, 1.4 GB):
      <a href="https://data.fieldmaps.io/global-admin/wld.gpkg.zip">
        https://data.fieldmaps.io/global-admin/wld.gpkg.zip
      </a>
    </li>
    <li>
      Boundaries (all levels, 2.2 GB):
      <a href="https://data.fieldmaps.io/global-admin/wld_levels.gpkg.zip">
        https://data.fieldmaps.io/global-admin/wld_levels.gpkg.zip
      </a>
    </li>
    <li>
      Attributes only:
      <a href="https://data.fieldmaps.io/global-admin/wld.xlsx.zip">
        https://data.fieldmaps.io/global-admin/wld.xlsx.zip
      </a>
    </li>
  </ul>
  <p>Special exports for particular use cases:</p>
  <ul>
    <li>
      Attributes only in HDX/ITOS format:
      <a href="https://data.fieldmaps.io/global-admin/hdx_attributes.zip">
        https://data.fieldmaps.io/global-admin/hdx_attributes.zip
      </a>
    </li>
  </ul>
  <h2 id="normalization-boundaries">Normalization: Boundaries</h2>
  <p>
    A common problem of merging spatial data from different sources is the
    existence of gaps and overlaps between sources. There are many ways to
    address this problem, with the approach taken here being to generate digital
    boundary files for each input. In this context, a digital boundary file is
    one that does not follow shorelines and international boundaries, but rather
    stretches out with simplified edges, intended for users to clip with their
    own shorelines and international boundaries. For example, Statistics Canada
    uses a digital boundary file when creating census blocks, later clipped with
    lakes and shorelines to derive a layer suitable for reference maps.
  </p>
  <p>
    <img
      src="https://raw.githubusercontent.com/fieldmaps/global-admin/master/images/cbf-vs-dbf.jpg"
      alt="cartographic vs digital boundary file" />
  </p>
  <h2 id="normalization-attributes">Normalization: Attributes</h2>
  <p>
    Just as with boundaries, merging attribute columns between sources with
    different schemas need to be conditioned so that columns align with each
    other. For a global level boundary file, the following data would be useful
    to access in a predicable manner:
  </p>
  <ul>
    <li>
      Names: Countries with more than one official language may have multiple
      names for places.
    </li>
    <li>
      Types: Administration divisions may be governed differently based on their
      status, such as with territories, autonomous regions, etc.
    </li>
    <li>
      Codes: Used for joining with additional data such as population statistics
      and other thematic data. A number of agencies have developed their own
      codes for giving areas unique IDs.
    </li>
  </ul>
  <h2 id="installation">Installation</h2>
  <p>
    This project has only been tested with macOS to date, compatibility with
    Windows 10 is not guarenteed. The minimum requrements for this project are
    Python 3 and pandas. See
    <a
      href="https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html">
      pandas documentation
    </a>
    for more details about installing this on your system. Before running,
    install pip dependancies:
  </p>
  <pre>
    <code class="lang-sh">
      pip3
      <span class="hljs-keyword">install</span>
      -r requirements.txt
    </code>
  </pre>
  <h2 id="usage">Usage</h2>
  <p>
    To replicate the results created by the download link, a
    <code>Makefile</code>
    is available to download input data too large to be stored in GitHub. To
    generate a new attribute dataset, the following commands must be run:
  </p>
  <ul>
    <li>
      <code>make get_attributes</code>
      : fetches a zip file hosted from an S3 bucket and extracts it to a local
      directory. This can be done manually if there are issues using this
      utility.
    </li>
    <li>
      <code>make build_attributes</code>
      : sequentially runs a series of 4 python scripts that import attributes
      from HDX and GADM, merge into a common dataset, and them re-export layers
      from all sources to the format originally found on HDX.
    </li>
  </ul>
  <h2 id="methodology-boundaries">Methodology: Boundaries</h2>
  <p>
    For those looking to replicate or create workflows of their own, the
    following serve as a high level overview of the steps carried out during
    spatial data processing to create the digital boundary file that is clipped
    with a global admin 0 layer such as the one from
    <a href="https://geonode.wfp.org/layers/geonode%3Awld_bnd_adm0">
      WFP GeoNode
    </a>
    .
  </p>
  <p>
    <img
      src="https://raw.githubusercontent.com/fieldmaps/global-admin/master/images/tza-1.png"
      alt="Input boundaries" />
  </p>
  <p>
    The data processing pipeline takes the most detailed admin level available
    as the input.
  </p>
  <p>
    <img
      src="https://raw.githubusercontent.com/fieldmaps/global-admin/master/images/tza-2.png"
      alt="Input boundaries" />
  </p>
  <p>
    From this input, the boundaries between admin regions are extended outwards
    using voronoi polygons.
  </p>
  <p>
    <img
      src="https://raw.githubusercontent.com/fieldmaps/global-admin/master/images/tza-3.png"
      alt="Input boundaries" />
  </p>
  <p>
    The original input is dissolved with the resulting voronoi polygons to
    create a borderless digital boundary file.
  </p>
  <p>
    <img
      src="https://raw.githubusercontent.com/fieldmaps/global-admin/master/images/tza-4.png"
      alt="Input boundaries" />
  </p>
  <p>
    This new layer can be clipped with any other admin 0 layer for that country.
  </p>
  <ol>
    <li>
      Extract the edges of the boundary file as a line, while retaining
      information about which part of the line corresponds to which admin area.
      From this input, we want to extend these edges outwards in an intelligent
      way that will fill in space far beyond the original boundaries.
      <ol>
        <li>
          Start with the most detailed admin level available from the original
          source, with all attributes stripped except for codes used for
          joining.
        </li>
        <li>Dissolve to a single admin 0 polygon.</li>
        <li>
          Convert both the most detailed admin level and the dissolved admin 0
          layer from polygons to lines.
        </li>
        <li>
          Intersect line layers together, retaining information about which line
          segment originated from which detailed admin level.
        </li>
      </ol>
    </li>
    <li>
      Extract points along the lines to be used in generating voronoi polygons.
      Due to how voronoi polygons are generated, input points cannot be
      overlapping, so the ends of lines need to be trimmed an extremely small
      amount to allow a gap in between them. For this project, very small is
      defined as 0.000001 degrees (approx. 10cm)
      <ol>
        <li>
          Apply a very small buffer to each line segment without dissolving
          results.
        </li>
        <li>Convert the buffers into lines.</li>
        <li>
          Intersect the buffer lines with the line segments used at the
          beginning of this part. Use a line intersection tool to create points
          where these two layers meet. This will result in points located a very
          small distance from the ends of each line.
        </li>
        <li>
          Using these points placed almost at the end of every line segment,
          generate a buffer of 0.000002 degrees. This is to ensure that points
          next to each other will have their buffers fully overlapping. Dissolve
          results.
        </li>
        <li>
          With these small buffers covering the ends of every line segment, use
          the difference tool to very slightly trim each line segment, so their
          ends no longer touch.
        </li>
      </ol>
    </li>
    <li>
      With a properly conditioned input line segment, extract sufficient points
      along the line. From testing multiple variables for point spacing, 0.0001
      degrees (approx. 10m) was the shortest spacing that did not produce
      abnormal artifacts in results for all countries tested. However,
      generating points at this density resulted in processing times of days, so
      an alternative was used by combining less processor intensive methods.
      <ol>
        <li>
          Points are generated regularly every 0.001 degrees (approx. 100m)
          along line segments.
        </li>
        <li>
          The input line segments were exploded so that every strait part along
          them became it&#39;s own feature.
        </li>
        <li>
          Points are generated by taking the centre of each exploded line part.
        </li>
        <li>
          Points generated in step 2.3 are combined with the steps above to
          create a single layer.
        </li>
      </ol>
    </li>
    <li>
      From these points spaced along the line, voronoi polygons intelligently
      extend outwards and allocate available space associated with the
      attributes of the edge point closest to it.
      <ol>
        <li>
          Generate voronoi polygons from the input points, filling an area
          double the size of the original bounding box of the input.
        </li>
        <li>Dissolve polygons that originate from the same admin polygon.</li>
        <li>
          Merge this dissolved layer with the original admin layer through a
          union.
        </li>
        <li>
          In the attribute table, in places where the original admin and the
          voronoi polygons intersect, ignore the voronoi attributes and use only
          the original. In places where there is only voronoi polygons, use
          those values. Merge polygons together that share the same attribute
          values.
        </li>
        <li>
          Apply topology cleaning to ensure the integrity of the final result.
        </li>
        <li>Create higher admin levels by dissolving based on attributes.</li>
        <li>Clip all layers to desired global admin 0 layer.</li>
      </ol>
    </li>
  </ol>
  <h2 id="methodology-attributes">Methodology: Attributes</h2>
  <p>Tabular data is split into the following sheets:</p>
  <ul>
    <li>join: ID codes used for describing hierarchal relations</li>
    <li>adm0: country level metadata</li>
    <li>adm1 - adm5: names, types, and codes for individual layers</li>
  </ul>
  <p>
    The join table uses ID codes that are generated uniquely for this project.
    ID&#39;s generated use the 3-letter ISO code to identify the country (admin
    0 level), followed by sequential blocks of 3 numbers for every admin level.
    For example, the following would represent the first admin units of each
    level for Tanzania:
  </p>
  <ul>
    <li>
      Admin 0:
      <code>TZA</code>
    </li>
    <li>
      Admin 1:
      <code>TZA001</code>
    </li>
    <li>
      Admin 2:
      <code>TZA001001</code>
    </li>
    <li>
      Admin 3:
      <code>TZA001001001</code>
    </li>
  </ul>
  <p>
    Codes are automatically generated sequentially and using this coding, so if
    the input admin 1 originally contained three regions coded (
    <code>TZ00</code>
    ,
    <code>TZ02</code>
    ,
    <code>TZ04</code>
    ), the output for this project would still be (
    <code>TZA001</code>
    ,
    <code>TZA002</code>
    ,
    <code>TZA003</code>
    ), with the original coding from the source captured in metadata. More
    information on attributes and coding to be added soon...
  </p>
</div>
