// src/routes/about.svelte
<svelte:head>
  <title>About | Fieldmaps.io</title>
</svelte:head>

<div class="content">
  <h2>About me</h2>
  <p>
    I've been fascinated with putting maps on the internet since first doing
    this at McGill University, which has led me to some wonderful and remote
    corners of the world. In the private sector, working with SparkGeo
    Consulting in Northern British Columbia on web app development and
    geospatial analytics. In the humanitarian sector, with REACH Initiative on
    missions in Jordan, South Sudan, and Nigeria. In these field missions, I
    started getting involved with information management in multiple clusters
    and working groups. In particular, creating common operational datasets with
    OCHA is what got me to start this site. Currently with the World Food
    Programme, I'm keeping this project active as a way to continue
    collaboration with all the people I've been in touch with in the past.
  </p>
  <h2>Acknowledgements</h2>
  <p>
    None of this would be possible without support from the following
    organizations, who have been instrumental in sharing data and giving
    countless hours of help over Skype:
  </p>
  <ul>
    <li>UN Office for the Coordination of Humanitarian Affairs (OCHA)</li>
    <li>UN World Food Programme (WFP)</li>
    <li>The Centre for Humanitarian Data</li>
    <li>
      University of Georgia, Information Technology Outreach Services (ITOS)
    </li>
    <li>REACH Initiative</li>
    <li>MapAction</li>
    <li>CartONG</li>
  </ul>
</div>

// src/components/content/about.tsx
import React from 'react';

export default () => (
  <>
    <h1 className="has-text-centered">About me</h1>
    <p>
      I've been fascinated with putting maps on the internet since first doing
      this at university, which has led me to some wonderful and remote corners
      of the world. In the private sector, working with SparkGeo Consulting in
      northern Canada on web app development and geospatial analytics. In the
      humanitarian sector, with REACH Initiative on missions in Jordan, South
      Sudan, and Nigeria. In these field missions, I started getting involved
      with information management in multiple clusters and working groups. In
      particular, creating common operational datasets with OCHA had me realize
      how valuable this kind of core infrastructure is by the people who rely on
      them. Currently with the World Food Programme, I'm contributing to this
      project in my personal time as a way to continue collaboration with all
      the people I've been in touch with in the past.
    </p>
    <h2 className="has-text-centered">Acknowledgements</h2>
    <p>
      None of this would be possible without the generous support from the
      following organizations, who's members have been instrumental in sharing
      data and giving countless hours of help online:
    </p>
    <ul>
      <li>UN Office for the Coordination of Humanitarian Affairs (OCHA)</li>
      <li>UN World Food Programme (WFP)</li>
      <li>The Centre for Humanitarian Data</li>
      <li>
        University of Georgia, Information Technology Outreach Services (ITOS)
      </li>
      <li>REACH Initiative</li>
      <li>MapAction</li>
      <li>CartONG</li>
    </ul>
  </>
);
