// src/lib/Metadata.svelte
<script lang="ts">
  const url = 'https://fieldmaps.io/';
  const img = 'https://fieldmaps.io/img/edge-matched-preview.png';
  const title = 'FieldMaps — Humanitarian Maps & Data';
  const description =
    'Mobile, offline, interactive reference maps & globally aggregated datasets for humanitarian use.';
</script>

<link rel="manifest" href="/manifest.webmanifest" />
<link rel="icon" type="image/png" href="/img/logo-192.png" />
<meta name="title" content={title} />
<meta name="description" content={description} />
<meta property="og:type" content="website" />
<meta property="og:url" content={url} />
<meta property="og:title" content={title} />
<meta property="og:description" content={description} />
<meta property="og:image" content={img} />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:url" content={url} />
<meta name="twitter:title" content={title} />
<meta name="twitter:description" content={description} />
<meta name="twitter:image" content={img} />

// src/components/common/metadata.tsx
import React from 'react';
import Helmet from 'react-helmet';

const url = 'https://fieldmaps.io/';
const img = 'https://fieldmaps.io/img/atlas-ssd-preview.png';
const title = 'Fieldmaps.io — Humanitarian Maps & Data';
const description =
  'Mobile, offline, interactive reference maps & globally aggregated datasets for humanitarian use.';

export default ({ page }) => (
  <Helmet>
    <title>{page} | Fieldmaps.io</title>
    <link rel="icon" type="image/png" href="img/logo-192.png" />
    <meta name="title" content={title} />
    <meta name="description" content={description} />
    <meta property="og:type" content="website" />
    <meta property="og:url" content={url} />
    <meta property="og:title" content={title} />
    <meta property="og:description" content={description} />
    <meta property="og:image" content={img} />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:url" content={url} />
    <meta name="twitter:title" content={title} />
    <meta name="twitter:description" content={description} />
    <meta name="twitter:image" content={img} />
  </Helmet>
);
