// src/components/common/header.tsx
import React from 'react';
import { Link } from 'gatsby';

export default ({ active }) => (
  <div className="tabs is-centered">
    <ul>
      <li className={active === '' ? 'is-active' : ''}>
        <Link to="/">home</Link>
      </li>
      <li className={active === 'data' ? 'is-active' : ''}>
        <Link to="/data">data</Link>
      </li>
      <li className={active === 'maps' ? 'is-active' : ''}>
        <Link to="/maps">maps</Link>
      </li>
      <li className={active === 'about' ? 'is-active' : ''}>
        <Link to="/about">about</Link>
      </li>
    </ul>
  </div>
);

// src/lib/components/Header.svelte
<script lang="ts">
  interface Props {
    active: string;
  }

  let { active }: Props = $props();
</script>

<div class="tabs is-centered">
  <ul>
    <li class={active === '' ? 'is-active' : ''}>
      <a href="/">home</a>
    </li>
    <li class={active === 'data' ? 'is-active' : ''}>
      <a href="/data">data</a>
    </li>
    <li class={active === 'maps' ? 'is-active' : ''}>
      <a href="/maps">maps</a>
    </li>
    <li class={active === 'about' ? 'is-active' : ''}>
      <a href="/about">about</a>
    </li>
  </ul>
</div>
