// src/components/common/header-data.tsx
import React from 'react';
import { Link } from 'gatsby';

export default ({ active }) => (
  <div className="tabs is-toggle is-centered">
    <ul>
      <li className={active === '' ? 'is-active' : ''}>
        <Link to="/data">edge-matched</Link>
      </li>
      <li className={active === 'adm0' ? 'is-active' : ''}>
        <Link to="/data/adm0">adm0</Link>
      </li>
      <li className={active === 'population' ? 'is-active' : ''}>
        <Link to="/data/population">population</Link>
      </li>
      <li className={active === 'cod' ? 'is-active' : ''}>
        <Link to="/data/cod">cod</Link>
      </li>
      <li className={active === 'geoboundaries' ? 'is-active' : ''}>
        <Link to="/data/geoboundaries">geoboundaries</Link>
      </li>
    </ul>
  </div>
);

// src/lib/components/HeaderData.svelte
<script lang="ts">
  export let active: string;
</script>

<div class="tabs is-toggle is-centered">
  <ul>
    <li class={active === '' ? 'is-active' : ''}>
      <a href="/data">edge-matched</a>
    </li>
    <li class={active === 'adm0' ? 'is-active' : ''}>
      <a href="/data/adm0">adm0</a>
    </li>
    <li class={active === 'population' ? 'is-active' : ''}>
      <a href="/data/population">population</a>
    </li>
    <li class={active === 'cod' ? 'is-active' : ''}>
      <a href="/data/cod">cod</a>
    </li>
    <li class={active === 'geoboundaries' ? 'is-active' : ''}>
      <a href="/data/geoboundaries">geoboundaries</a>
    </li>
  </ul>
</div>
